# Generated by Django 5.0.6 on 2024-07-03 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('companionship', models.CharField(max_length=100)),
                ('daily_activities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HealthMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('bgl', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('o2', models.CharField(max_length=100)),
                ('pulse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Housekeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('bathroom', models.CharField(default='Bathroom', max_length=100, null=True)),
                ('laundry', models.CharField(default='Laundry', max_length=100, null=True)),
                ('bedroom', models.CharField(default='Bedroom', max_length=100, null=True)),
                ('kitchen', models.CharField(default='kitchen', max_length=100, null=True)),
                ('living', models.CharField(default='Living Room', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilityAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('transfer', models.CharField(max_length=100)),
                ('mobility', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionHydration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('feeding_assistance', models.CharField(max_length=100)),
                ('food_intake', models.CharField(max_length=100)),
                ('fluid_intake', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('bathing', models.CharField(max_length=100)),
                ('dressing', models.CharField(max_length=100)),
                ('toileting', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('house_street', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('med_background', models.CharField(max_length=250)),
                ('care_plan', models.CharField(max_length=2500, null=True)),
                ('contact_first', models.CharField(max_length=50)),
                ('contact_last', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('contact_rel', models.CharField(max_length=20)),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.CharField(default='Bathroom', max_length=100)),
                ('activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.activities')),
                ('health_monitoring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.healthmonitoring')),
                ('housekeeping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.housekeeping')),
                ('mobility_assistance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.mobilityassistance')),
                ('nutrition_hydration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.nutritionhydration')),
                ('personal_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.personalcare')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('progress_notes', models.CharField(max_length=2500)),
                ('care_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.caretype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record')),
            ],
        ),
        migrations.AddField(
            model_name='personalcare',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='nutritionhydration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='mobilityassistance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='healthmonitoring',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='activities',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
    ]
