# Generated by Django 5.0.6 on 2024-07-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressnotes',
            old_name='person',
            new_name='persons',
        ),
    ]
