# Generated by Django 5.0.6 on 2024-07-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_persons_progressnotes_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretype',
            name='bathroom',
        ),
        migrations.AlterField(
            model_name='caretype',
            name='activities',
            field=models.CharField(default='Bathroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='health_monitoring',
            field=models.CharField(default='Bathroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='housekeeping',
            field=models.CharField(default='Bathroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='mobility_assistance',
            field=models.CharField(default='Bathroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='nutrition_hydration',
            field=models.CharField(default='Bathroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='personal_care',
            field=models.CharField(default='Bathroom', max_length=100),
        ),
        migrations.AlterField(
            model_name='progressnotes',
            name='care_type',
            field=models.CharField(choices=[('personal_care', 'Personal Care'), ('mobility_assistance', 'Mobility Assistance'), ('nutrition_hydration', 'Nutrition and Hydration'), ('health_monitoring', 'Health Monitoring'), ('activities', 'Activities'), ('housekeeping', 'Housekeeping')], max_length=20),
        ),
    ]
