# Generated by Django 5.0.6 on 2024-07-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_caretype_bathroom_alter_caretype_activities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressnotes',
            old_name='care_type',
            new_name='care_types',
        ),
    ]
